// Japanese Verb Database
// Contains verbs for lessons and practices, classified by group and conjugation rules.

window.VERB_DATABASE = [
  // --- Group 1 (Godan Verbs) ---
  {
    kanji: "買う",
    hiragana: "かう",
    romaji: "kau",
    english: "to buy",
    group: 1,
    subtype: "u",
    teForm: "買って",
    teRomaji: "katte",
    teHiragana: "かって",
    taForm: "買った",
    taRomaji: "katta",
    taHiragana: "かった",
    explanation: "Verbs ending in ~u (う) conjugate to -te/-ta by dropping 'u' and adding 'tte' / 'tta'."
  },
  {
    kanji: "言う",
    hiragana: "いう",
    romaji: "iu",
    english: "to say",
    group: 1,
    subtype: "u",
    teForm: "言って",
    teRomaji: "itte",
    teHiragana: "いって",
    taForm: "言った",
    taRomaji: "itta",
    taHiragana: "いった",
    explanation: "Verbs ending in ~u (う) conjugate to -te/-ta by dropping 'u' and adding 'tte' / 'tta'."
  },
  {
    kanji: "待つ",
    hiragana: "まつ",
    romaji: "matsu",
    english: "to wait",
    group: 1,
    subtype: "tsu",
    teForm: "待って",
    teRomaji: "matte",
    teHiragana: "まって",
    taForm: "待った",
    taRomaji: "matta",
    taHiragana: "まった",
    explanation: "Verbs ending in ~tsu (つ) conjugate to -te/-ta by dropping 'tsu' and adding 'tte' / 'tta'."
  },
  {
    kanji: "立つ",
    hiragana: "たつ",
    romaji: "tatsu",
    english: "to stand",
    group: 1,
    subtype: "tsu",
    teForm: "立って",
    teRomaji: "tatte",
    teHiragana: "たって",
    taForm: "立った",
    taRomaji: "tatta",
    taHiragana: "たった",
    explanation: "Verbs ending in ~tsu (つ) conjugate to -te/-ta by dropping 'tsu' and adding 'tte' / 'tta'."
  },
  {
    kanji: "取る",
    hiragana: "とる",
    romaji: "toru",
    english: "to take",
    group: 1,
    subtype: "ru",
    teForm: "取って",
    teRomaji: "totte",
    teHiragana: "とって",
    taForm: "取った",
    taRomaji: "totta",
    taHiragana: "とった",
    explanation: "Verbs ending in ~ru (る) conjugate to -te/-ta by dropping 'ru' and adding 'tte' / 'tta'."
  },
  {
    kanji: "帰る",
    hiragana: "かえる",
    romaji: "kaeru",
    english: "to return / go home",
    group: 1,
    subtype: "ru", // Exception: looks like an Ichidan (~eru), but conjugates as Godan!
    teForm: "帰って",
    teRomaji: "kaette",
    teHiragana: "かえって",
    taForm: "帰った",
    taRomaji: "kaetta",
    taHiragana: "かえった",
    isException: true,
    explanation: "WARNING: 'kaeru' looks like an Ichidan verb because of ~eru, but it is actually a Group 1 (Godan) verb! It conjugates with 'tte'/'tta'."
  },
  {
    kanji: "遊ぶ",
    hiragana: "あそぶ",
    romaji: "asobu",
    english: "to play",
    group: 1,
    subtype: "bu",
    teForm: "遊んで",
    teRomaji: "asonde",
    teHiragana: "あそんで",
    taForm: "遊んだ",
    taRomaji: "asonda",
    taHiragana: "あそんだ",
    explanation: "Verbs ending in ~bu (ぶ) conjugate to -te/-ta by dropping 'bu' and adding 'nde' / 'nda'."
  },
  {
    kanji: "呼ぶ",
    hiragana: "よぶ",
    romaji: "yobu",
    english: "to call",
    group: 1,
    subtype: "bu",
    teForm: "呼んで",
    teRomaji: "yonde",
    teHiragana: "よんで",
    taForm: "呼んだ",
    taRomaji: "yonda",
    taHiragana: "よんだ",
    explanation: "Verbs ending in ~bu (ぶ) conjugate to -te/-ta by dropping 'bu' and adding 'nde' / 'nda'."
  },
  {
    kanji: "読む",
    hiragana: "よむ",
    romaji: "yomu",
    english: "to read",
    group: 1,
    subtype: "mu",
    teForm: "読んで",
    teRomaji: "yonde",
    teHiragana: "よんで",
    taForm: "読んだ",
    taRomaji: "yonda",
    taHiragana: "よんだ",
    explanation: "Verbs ending in ~mu (む) conjugate to -te/-ta by dropping 'mu' and adding 'nde' / 'nda'."
  },
  {
    kanji: "飲む",
    hiragana: "のむ",
    romaji: "nomu",
    english: "to drink",
    group: 1,
    subtype: "mu",
    teForm: "飲んで",
    teRomaji: "nonde",
    teHiragana: "のんで",
    taForm: "飲んだ",
    taRomaji: "nonda",
    taHiragana: "のんだ",
    explanation: "Verbs ending in ~mu (む) conjugate to -te/-ta by dropping 'mu' and adding 'nde' / 'nda'."
  },
  {
    kanji: "死ぬ",
    hiragana: "しぬ",
    romaji: "shinu",
    english: "to die",
    group: 1,
    subtype: "nu",
    teForm: "死んで",
    teRomaji: "shinde",
    teHiragana: "しんで",
    taForm: "死んだ",
    taRomaji: "shinda",
    taHiragana: "しんだ",
    explanation: "Shinu is the only common verb ending in ~nu (ぬ). It conjugates to -te/-ta by dropping 'nu' and adding 'nde' / 'nda'."
  },
  {
    kanji: "書く",
    hiragana: "かく",
    romaji: "kaku",
    english: "to write",
    group: 1,
    subtype: "ku",
    teForm: "書いて",
    teRomaji: "kaite",
    teHiragana: "かいて",
    taForm: "書いた",
    taRomaji: "kaita",
    taHiragana: "かいた",
    explanation: "Verbs ending in ~ku (く) conjugate to -te/-ta by dropping 'ku' and adding 'ite' / 'ita'."
  },
  {
    kanji: "行く",
    hiragana: "いく",
    romaji: "iku",
    english: "to go",
    group: 1,
    subtype: "ku",
    teForm: "行って",
    teRomaji: "itte",
    teHiragana: "いって",
    taForm: "行った",
    taRomaji: "itta",
    taHiragana: "いった",
    isException: true,
    explanation: "EXCEPTION: Although 'iku' ends in ~ku, it conjugates with 'tte' / 'tta' (行って / 行った) rather than 'ite' / 'ita'."
  },
  {
    kanji: "泳ぐ",
    hiragana: "およぐ",
    romaji: "oyogu",
    english: "to swim",
    group: 1,
    subtype: "gu",
    teForm: "泳いで",
    teRomaji: "oyoide",
    teHiragana: "およいで",
    taForm: "泳いだ",
    taRomaji: "oyoida",
    taHiragana: "およいだ",
    explanation: "Verbs ending in ~gu (ぐ) conjugate to -te/-ta by dropping 'gu' and adding 'ide' / 'ida'."
  },
  {
    kanji: "話す",
    hiragana: "はなす",
    romaji: "hanasu",
    english: "to speak",
    group: 1,
    subtype: "su",
    teForm: "話して",
    teRomaji: "hanashite",
    teHiragana: "はなして",
    taForm: "話した",
    taRomaji: "hanashita",
    taHiragana: "はなした",
    explanation: "Verbs ending in ~su (す) conjugate to -te/-ta by dropping 'su' and adding 'shite' / 'shita'."
  },

  // --- Group 2 (Ichidan Verbs) ---
  {
    kanji: "食べる",
    hiragana: "たべる",
    romaji: "taberu",
    english: "to eat",
    group: 2,
    subtype: "ru-ichidan",
    teForm: "食べて",
    teRomaji: "tabete",
    teHiragana: "たべて",
    taForm: "食べた",
    taRomaji: "tabeta",
    taHiragana: "たべた",
    explanation: "Group 2 (Ichidan) verbs conjugate simply by dropping the trailing 'ru' (る) and replacing it with 'te' or 'ta'."
  },
  {
    kanji: "見る",
    hiragana: "みる",
    romaji: "miru",
    english: "to see / watch",
    group: 2,
    subtype: "ru-ichidan",
    teForm: "見て",
    teRomaji: "mite",
    teHiragana: "みて",
    taForm: "見た",
    taRomaji: "mita",
    taHiragana: "みた",
    explanation: "Group 2 (Ichidan) verbs conjugate simply by dropping the trailing 'ru' (る) and replacing it with 'te' or 'ta'."
  },
  {
    kanji: "開ける",
    hiragana: "あける",
    romaji: "akeru",
    english: "to open",
    group: 2,
    subtype: "ru-ichidan",
    teForm: "開けて",
    teRomaji: "akete",
    teHiragana: "あけて",
    taForm: "開けた",
    taRomaji: "aketa",
    taHiragana: "あけた",
    explanation: "Group 2 (Ichidan) verbs conjugate simply by dropping the trailing 'ru' (る) and replacing it with 'te' or 'ta'."
  },

  // --- Group 3 (Irregular Verbs) ---
  {
    kanji: "する",
    hiragana: "する",
    romaji: "suru",
    english: "to do",
    group: 3,
    subtype: "irregular",
    teForm: "して",
    teRomaji: "shite",
    teHiragana: "して",
    taForm: "した",
    taRomaji: "shita",
    taHiragana: "した",
    explanation: "Irregular verb 'suru' conjugates directly into 'shite' (て form) and 'shita' (た form)."
  },
  {
    kanji: "来る",
    hiragana: "くる",
    romaji: "kuru",
    english: "to come",
    group: 3,
    subtype: "irregular",
    teForm: "来て",
    teRomaji: "kite",
    teHiragana: "きて",
    taForm: "来た",
    taRomaji: "kita",
    taHiragana: "きた",
    explanation: "Irregular verb 'kuru' (来る) changes its stem vowel, conjugating to 'kite' (来て) / 'kita' (来た)."
  }
];
